import { describe, expect, it } from 'vitest';
import { renderWranglerConfig, serializeWranglerConfig } from '../src/render.js';
import type { ResourceRefs, VendaProject } from '../src/project.js';

const resources: ResourceRefs = {
  d1: { name: 'cms-content', id: 'd1-id' },
  kv: { title: 'cms-cache', id: 'kv-id' },
  r2: { name: 'cms-media' }
};

describe('Wrangler config rendering', () => {
  it('renders a same-origin SPA Worker with the install bindings', () => {
    const project: VendaProject = { name: 'cms', accountId: 'account-id', adminEmail: 'admin@example.com' };
    const config = renderWranglerConfig(project, resources, '.venda/versions/0.1.0', '0.1.0');
    expect(config.name).toBe('cms');
    expect(config.main).toBe('.venda/versions/0.1.0/worker/index.js');
    expect(config.assets).toEqual({
      directory: '.venda/versions/0.1.0/admin',
      binding: 'ASSETS',
      not_found_handling: 'single-page-application',
      run_worker_first: ['/api/*']
    });
    expect(config.d1_databases).toEqual([{ binding: 'VENDA_DB', database_name: 'cms-content', database_id: 'd1-id', migrations_dir: '.venda/versions/0.1.0/migrations' }]);
    expect(config.kv_namespaces).toEqual([{ binding: 'VENDA_CACHE', id: 'kv-id' }]);
    expect(config.r2_buckets).toEqual([{ binding: 'VENDA_MEDIA', bucket_name: 'cms-media' }]);
  });

  it('sets a custom domain and optional admin origins', () => {
    const project: VendaProject = { name: 'cms', accountId: 'account-id', adminEmail: 'admin@example.com', domain: 'cms.example.com', adminOrigins: ['https://site.example.com'] };
    const config = renderWranglerConfig(project, resources, '.venda/versions/0.1.0', '0.1.0');
    expect(config.routes).toEqual([{ pattern: 'cms.example.com', custom_domain: true }]);
    expect(config.workers_dev).toBe(false);
    expect(config.vars).toMatchObject({ ADMIN_ORIGINS: 'https://site.example.com', VENDA_VERSION: '0.1.0' });
    expect(serializeWranglerConfig(config)).toContain('Generated by the venda CLI');
  });
});
