import type { ResourceRefs, VendaProject } from './project.js';

export const WRANGLER_FILE = 'wrangler.jsonc';

// Matches the compatibility date the Venda Worker is developed and tested against.
const COMPATIBILITY_DATE = '2026-09-22';

/**
 * Wrangler config for one install: a single Worker serving the admin SPA from
 * static assets and the API under /api, bound to the install's own resources.
 * `releaseDir` is relative to the project directory (e.g. `.venda/versions/0.1.0`).
 */
export function renderWranglerConfig(project: VendaProject, resources: ResourceRefs, releaseDir: string, version: string): Record<string, unknown> {
  const vars: Record<string, string> = { ADMIN_EMAIL: project.adminEmail, VENDA_VERSION: version };
  if (project.adminOrigins?.length) vars.ADMIN_ORIGINS = project.adminOrigins.join(',');

  return {
    name: project.name,
    account_id: project.accountId,
    main: `${releaseDir}/worker/index.js`,
    compatibility_date: COMPATIBILITY_DATE,
    compatibility_flags: ['nodejs_compat'],
    assets: {
      directory: `${releaseDir}/admin`,
      binding: 'ASSETS',
      not_found_handling: 'single-page-application',
      run_worker_first: ['/api/*']
    },
    vars,
    d1_databases: [{ binding: 'VENDA_DB', database_name: resources.d1.name, database_id: resources.d1.id, migrations_dir: `${releaseDir}/migrations` }],
    kv_namespaces: [{ binding: 'VENDA_CACHE', id: resources.kv.id }],
    r2_buckets: [{ binding: 'VENDA_MEDIA', bucket_name: resources.r2.name }],
    ...(project.domain ? { routes: [{ pattern: project.domain, custom_domain: true }], workers_dev: false } : { workers_dev: true }),
    observability: { enabled: true }
  };
}

export function serializeWranglerConfig(config: Record<string, unknown>): string {
  return `// Generated by the venda CLI from venda.json on every deploy.\n// Edit venda.json instead; changes here are overwritten.\n${JSON.stringify(config, null, 2)}\n`;
}
